# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime, QDate, Qt
import psutil
from PyQt5.QtWidgets import QFileDialog



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1890, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1890, 960))
        MainWindow.setMaximumSize(QtCore.QSize(1890, 960))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-410, -220, 2480, 1181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("New/173836.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 130, 800, 650))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("New/Hologram 3.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 431, 481))
        self.label_2.setStyleSheet("border:1px solid #00ff00;\n""font-size:20px;\n""color:#00ff00;\n""font-family:\'Consolas\'")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.label_2.setWordWrap(True)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1700, 10, 181, 61))
        self.label_3.setStyleSheet("color:#00ff00;\n"
"font-size:34px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(850, 10, 250, 50))
        self.label_5.setStyleSheet("color:#00ff00;\nfont-size:40px;\nfont-family:\'Consolas\';\npadding:5px 10px;\n")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 381, 381))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("New/75lD.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1390, 200, 471, 461))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("New/2number.gif"))
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(450, 790, 1170, 161))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("New/sw.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("sw")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1630, 800, 231, 81))
        self.pushButton.setStyleSheet("font-size:40px;\n"
                                      "background-color:#292E49;\n"
                                      "color:#FFE000;\n")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("START")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(1500, 150, 281, 611))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QTimer()  # timer
        self.timer.timeout.connect(self.showTime)
        self.timer.start(1000)

    def showTime(self):
        currentTime = QTime.currentTime()
        displayTxt = currentTime.toString('hh:mm:ss')
        self.label_3.setText(displayTxt)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZIRA"))
        self.label_5.setText(_translate("MainWindow", "ZIRA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
